### ISSUE TITLE
pip install vext.pygtk fails on homebrew

### ISSUE THREAD

**Issue by stuaxo** [stuaxo/vext#29]
NOTE:  Tried updating pip + setuptools in a virtualenv, and had the same results

```
Mac-mini:~ stu$ virtualenv env
New python executable in env/bin/python
Installing setuptools, pip, wheel...done.
Mac-mini:~ stu$ . ./env/bin/activate
(env)Mac-mini:~ stu$ python
Python 2.7.11 (default, Dec  5 2015, 23:52:42) 
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pygtk
>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
(env)Mac-mini:~ stu$ 
(env)Mac-mini:~ stu$ pip install vext.pygtk
Collecting vext.pygtk
  Downloading vext.pygtk-0.5.14.tar.gz
Collecting vext>=0.5.14 (from vext.pygtk)
  Downloading vext-0.5.15.tar.gz
Collecting pyyaml==3.11 (from vext>=0.5.14->vext.pygtk)
  Downloading PyYAML-3.11.tar.gz (248kB)
    100% |████████████████████████████████| 249kB 580kB/s 
Building wheels for collected packages: vext.pygtk, vext, pyyaml
  Running setup.py bdist_wheel for vext.pygtk
  Complete output from command /Users/stu/env/bin/python -c "import setuptools;__file__='/private/var/folders/c0/t9bv7c_57d13mnr0r_p9v9780000gn/T/pip-build-C_ptoh/vext.pygtk/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /var/folders/c0/t9bv7c_57d13mnr0r_p9v9780000gn/T/tmpkyUsEupip-wheel-:
  running bdist_wheel
  running build
  installing to build/bdist.macosx-10.10-x86_64/wheel
  running install
  Collecting vext>=0.5.14
    Using cached vext-0.5.15.tar.gz
  Collecting pyyaml==3.11 (from vext>=0.5.14)
    Using cached PyYAML-3.11.tar.gz
  Building wheels for collected packages: vext, pyyaml
    Running setup.py bdist_wheel for vext
    Stored in directory: /Users/stu/Library/Caches/pip/wheels/bf/08/bc/8ebe62a012379dd80af34011bfb1529f5a6b26819ea0f09974
    Running setup.py bdist_wheel for pyyaml
    Stored in directory: /Users/stu/Library/Caches/pip/wheels/fa/db/f6/dee55793d344f1706dc4a5a693298f0115241d1085cc212364
  Successfully built vext pyyaml
  Installing collected packages: pyyaml, vext
  Successfully installed pyyaml-3.11 vext-0.5.15
  You are using pip version 7.1.2, however version 8.0.2 is available.
  You should consider upgrading via the 'pip install --upgrade pip' command.
  vext.gi Install
  Checking .pth file support in build/bdist.macosx-10.10-x86_64/wheel/vext.pygtk-0.5.14.data/purelib/
  /Users/stu/env/bin/python -E -c pass
  Traceback (most recent call last):
    File "/Users/stu/env/bin/../lib/python2.7/site.py", line 703, in <module>
      main()
    File "/Users/stu/env/bin/../lib/python2.7/site.py", line 694, in main
      execsitecustomize()
    File "/Users/stu/env/bin/../lib/python2.7/site.py", line 548, in execsitecustomize
      import sitecustomize
    File "/Users/stu/env/lib/python2.7/site-packages/vext/gatekeeper/__init__.py", line 157, in __init__
      sitedir = getsyssitepackages()
    File "/Users/stu/env/lib/python2.7/site-packages/vext/env/__init__.py", line 96, in getsyssitepackages
      output = run()
    File "/Users/stu/env/lib/python2.7/site-packages/vext/env/__init__.py", line 41, in call_f
      output = subprocess.check_output(cmd, env=env).decode('utf-8')
    File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 566, in check_output
      process = Popen(stdout=PIPE, *popenargs, **kwargs)
    File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
      errread, errwrite)
    File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
      raise child_exception
  AttributeError: 'NoneType' object has no attribute 'rfind'
  error: command '/Users/stu/env/bin/python' failed with exit status 1

  ----------------------------------------
  Failed building wheel for vext.pygtk
  Running setup.py bdist_wheel for vext
  Complete output from command /Users/stu/env/bin/python -c "import setuptools;__file__='/private/var/folders/c0/t9bv7c_57d13mnr0r_p9v9780000gn/T/pip-build-C_ptoh/vext/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /var/folders/c0/t9bv7c_57d13mnr0r_p9v9780000gn/T/tmpufyDRYpip-wheel-:
  Traceback (most recent call last):
    File "/Users/stu/env/bin/../lib/python2.7/site.py", line 703, in <module>
      main()
    File "/Users/stu/env/bin/../lib/python2.7/site.py", line 694, in main
      execsitecustomize()
    File "/Users/stu/env/bin/../lib/python2.7/site.py", line 548, in execsitecustomize
      import sitecustomize
    File "/Users/stu/env/lib/python2.7/site-packages/vext/gatekeeper/__init__.py", line 157, in __init__
      sitedir = getsyssitepackages()
    File "/Users/stu/env/lib/python2.7/site-packages/vext/env/__init__.py", line 96, in getsyssitepackages
      output = run()
    File "/Users/stu/env/lib/python2.7/site-packages/vext/env/__init__.py", line 41, in call_f
      output = subprocess.check_output(cmd, env=env).decode('utf-8')
    File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 566, in check_output
      process = Popen(stdout=PIPE, *popenargs, **kwargs)
    File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
      errread, errwrite)
    File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
      raise child_exception
  AttributeError: 'NoneType' object has no attribute 'rfind'

  ----------------------------------------
  Failed building wheel for vext
  Running setup.py bdist_wheel for pyyaml
  Complete output from command /Users/stu/env/bin/python -c "import setuptools;__file__='/private/var/folders/c0/t9bv7c_57d13mnr0r_p9v9780000gn/T/pip-build-C_ptoh/pyyaml/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /var/folders/c0/t9bv7c_57d13mnr0r_p9v9780000gn/T/tmpq13Jotpip-wheel-:
  Traceback (most recent call last):
    File "/Users/stu/env/bin/../lib/python2.7/site.py", line 703, in <module>
      main()
    File "/Users/stu/env/bin/../lib/python2.7/site.py", line 694, in main
      execsitecustomize()
    File "/Users/stu/env/bin/../lib/python2.7/site.py", line 548, in execsitecustomize
      import sitecustomize
    File "/Users/stu/env/lib/python2.7/site-packages/vext/gatekeeper/__init__.py", line 157, in __init__
      sitedir = getsyssitepackages()
    File "/Users/stu/env/lib/python2.7/site-packages/vext/env/__init__.py", line 96, in getsyssitepackages
      output = run()
    File "/Users/stu/env/lib/python2.7/site-packages/vext/env/__init__.py", line 41, in call_f
      output = subprocess.check_output(cmd, env=env).decode('utf-8')
    File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 566, in check_output
      process = Popen(stdout=PIPE, *popenargs, **kwargs)
    File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
      errread, errwrite)
    File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
      raise child_exception
  AttributeError: 'NoneType' object has no attribute 'rfind'

  ----------------------------------------
  Failed building wheel for pyyaml
Failed to build vext.pygtk vext pyyaml
Installing collected packages: pyyaml, vext, vext.pygtk
  Running setup.py install for pyyaml
    Complete output from command /Users/stu/env/bin/python -c "import setuptools, tokenize;__file__='/private/var/folders/c0/t9bv7c_57d13mnr0r_p9v9780000gn/T/pip-build-C_ptoh/pyyaml/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/c0/t9bv7c_57d13mnr0r_p9v9780000gn/T/pip-pJRLG0-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/stu/env/bin/../include/site/python2.7/pyyaml:
    Traceback (most recent call last):
      File "/Users/stu/env/bin/../lib/python2.7/site.py", line 703, in <module>
        main()
      File "/Users/stu/env/bin/../lib/python2.7/site.py", line 694, in main
        execsitecustomize()
      File "/Users/stu/env/bin/../lib/python2.7/site.py", line 548, in execsitecustomize
        import sitecustomize
      File "/Users/stu/env/lib/python2.7/site-packages/vext/gatekeeper/__init__.py", line 157, in __init__
        sitedir = getsyssitepackages()
      File "/Users/stu/env/lib/python2.7/site-packages/vext/env/__init__.py", line 96, in getsyssitepackages
        output = run()
      File "/Users/stu/env/lib/python2.7/site-packages/vext/env/__init__.py", line 41, in call_f
        output = subprocess.check_output(cmd, env=env).decode('utf-8')
      File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 566, in check_output
        process = Popen(stdout=PIPE, *popenargs, **kwargs)
      File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
        errread, errwrite)
      File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
        raise child_exception
    AttributeError: 'NoneType' object has no attribute 'rfind'

    ----------------------------------------
Command "/Users/stu/env/bin/python -c "import setuptools, tokenize;__file__='/private/var/folders/c0/t9bv7c_57d13mnr0r_p9v9780000gn/T/pip-build-C_ptoh/pyyaml/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/c0/t9bv7c_57d13mnr0r_p9v9780000gn/T/pip-pJRLG0-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/stu/env/bin/../include/site/python2.7/pyyaml" failed with error code 1 in /private/var/folders/c0/t9bv7c_57d13mnr0r_p9v9780000gn/T/pip-build-C_ptoh/pyyaml
You are using pip version 7.1.2, however version 8.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(env)Mac-mini:~ stu$ 
```

**Comment by stuaxo** [comment]
In the getsyssitepackages, the variable "python" which should point at a python interpreter is None.

```ipdb> u

> /Users/stu/vext/vext/env/**init**.py(41)call_f()```

**Comment by stuaxo** [comment]
```
ipdb> cmd
[None, '-c', 'def run(*args):\n    import site\n    return site.getsitepackages()\n\nimport sys\nargs = sys.argv[1:]\nresult = run(*args)\nprint("%r" % result)\n']
```

**Comment by stuaxo** [comment]
findsyspy returns None, which is not correct

```
from vext import env
env.findsyspy() == None
Out[8]: True
```

**Comment by andreubotella** [comment]
I think I ran into the same bug when testing in Windows, and it's because the filesystem is case-insensitive. Changing line 115 in `env/__init__.py` to:

```
                normcase(folder).startswith(normcase(prefix)) and\
```

does it for me. (Plus adding `normcase` to the `os.path` imports, ofc.) But I don't know if there's some other code doing path comparisons that would also need fixing.

I didn't report this earlier because once that's fixed, there's another Windows bug specific to `vext.gi` which I'm still trying to figure out.

**Comment by stuaxo** [comment]
Cheers, I patched it - but then a uploaded it probably a little too quickly as it looks like getsyssitepackages has a similar problem, which I don't have time to look at right now.

I added a sanity check for findsyspy() != None in install_importer() - vext shouldn't be able to break the running python env if it breaks.

Great work looking at Windows, adding in Python + Gtk can get pretty knarly at times.

**Comment by stuaxo** [comment]
Ah, just realised that patch to findsyspy wasn't quite enough in my own python env (or more likely I bodged the fix).

**Comment by andreubotella** [comment]
The patch seems to work on my Windows box.

**Comment by stuaxo** [comment]
Cool.     

Any chance of opening a ticket for the issue with gi, with the output of the commands below ?

```
set VEXT_DEBUG=1
python -c "import gi"
```

**Comment by andreubotella** [comment]
I wanted to check first if the issue also applied to PyQt4/5. I'll
test it now and open it. But VEXT_DEBUG won't help in any case, it's a
native libraries thing.

**Comment by anthrotype** [comment]
`findsyspy` returns None (making subprocess fail) when running inside a virtual environment whose `orig-prefix.txt` points to the prefix of a homebrew Python, such as:

```
/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7
```

The `findsyspy` function attempts to find the folder where the system python is located by checking for each folder in the $PATH whether it starts with the original prefix; however, this doesn't work in this case, since that prefix is not in the $PATH. Adding `normpath` as suggested above won't fix the issue on OS X.

Unfortunately, I have no idea what the fix should be...
Let me know if I could be of any help.
Thanks.

**Comment by stuaxo** [comment]
It looks like under homebrew, orig-prefix is no longer in PATH - so we probably need an extra bit of logic at the end of findsyspy

I tried adding this code to the end of findsyspy: -

``` python
        # under homebrew, might not be in the PATH
        if isfile(join(prefix, "bin", sys.executable)):
            return join(prefix, "bin", sys.executable)
```

It hits another bug which causes recursion, having a look at that might be helpful, as I don't have great access to OSX.

Apart from that, writing tests - or any ideas about tests, for findsyspy, would be really helpful.

**Comment by stuaxo** [comment]
^ oops hang on, that code is clearly wrong :)

**Comment by stuaxo** [comment]
^ hm - this incorrect for me as it is returning the virtualenvs python executable, needs some more debugging..

**Comment by stuaxo** [comment]
Here is a possible fix, that works for me (TM) - let me know if it works, if it does I'll do a new release.

https://github.com/stuaxo/vext/blob/master/vext/env/__init__.py#L120

**Comment by anthrotype** [comment]
hmm.
shouldn't that be:

``` diff
-if isfile(join(prefix, "bin", sys.executable))
+if isfile(join(prefix, "bin", python))
     return join(prefix, "bin", python)
```

**Comment by stuaxo** [comment]
Good catch :) - patched.

**Comment by anthrotype** [comment]
LGTM

**Comment by stuaxo** [comment]
Have made a release with this fix.     

Initial test seems to work, feel free to re-open this ticket if there are any issues.

**Comment by anthrotype** [comment]
thanks!
