### ISSUE TITLE
Error using pip install vext.gi in pyenv

### ISSUE THREAD

**Issue by Jackovic** [stuaxo/vext#61]
Hello, I just follow the README, and enter in my virtualenv :

`$ pip install vext.gi`

But I get :
`Error processing line 1 of /home/pi/.pyenv/versions/3.7.0/envs/mon_environnement370/lib/python3.7/site-packages/ruamel.yaml-0.16.5-py3.6-nspkg.pth:

  Traceback (most recent call last):
    File "<frozen importlib._bootstrap_external>", line 1219, in _path_importer_cache
  KeyError: 'VextFinder.PATH_TRIGGER'
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/home/pi/.pyenv/versions/3.7.0/lib/python3.7/site.py", line 168, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
    File "<frozen importlib._bootstrap_external>", line 1127, in __contains__
    File "<frozen importlib._bootstrap_external>", line 1105, in _recalculate
    File "<frozen importlib._bootstrap_external>", line 1249, in _get_spec
    File "<frozen importlib._bootstrap_external>", line 1221, in _path_importer_cache
    File "<frozen importlib._bootstrap_external>", line 1197, in _path_hooks
    File "/home/pi/.pyenv/versions/3.7.0/envs/mon_environnement370/lib/python3.7/site-packages/vext/gatekeeper/__init__.py", line 227, in __init__
      sitedir = getsyssitepackages()
    File "/home/pi/.pyenv/versions/3.7.0/envs/mon_environnement370/lib/python3.7/site-packages/vext/env/__init__.py", line 99, in getsyssitepackages
      output = run()
    File "/home/pi/.pyenv/versions/3.7.0/envs/mon_environnement370/lib/python3.7/site-packages/vext/env/__init__.py", line 42, in call_f
      output = subprocess.check_output(cmd, env=env).decode('utf-8')
    File "/home/pi/.pyenv/versions/3.7.0/lib/python3.7/subprocess.py", line 376, in check_output
      **kwargs).stdout
    File "/home/pi/.pyenv/versions/3.7.0/lib/python3.7/subprocess.py", line 453, in run
      with Popen(*popenargs, **kwargs) as process:
    File "/home/pi/.pyenv/versions/3.7.0/lib/python3.7/subprocess.py", line 756, in __init__
      restore_signals, start_new_session)
    File "/home/pi/.pyenv/versions/3.7.0/lib/python3.7/subprocess.py", line 1413, in _execute_child
      executable = os.fsencode(executable)
    File "/home/pi/.pyenv/versions/3.7.0/lib/python3.7/os.py", line 809, in fsencode
      filename = fspath(filename)  # Does type-checking of 'filename'.
  TypeError: expected str, bytes or os.PathLike object, not NoneType

Remainder of file ignored
Error in sitecustomize; set PYTHONVERBOSE for traceback:
TypeError: expected str, bytes or os.PathLike object, not NoneType
Failed checking if argv[0] is an import path entry
Traceback (most recent call last):
  File "/home/pi/.pyenv/versions/3.7.0/envs/mon_environnement370/lib/python3.7/site-packages/vext/gatekeeper/__init__.py", line 227, in __init__
    sitedir = getsyssitepackages()
  File "/home/pi/.pyenv/versions/3.7.0/envs/mon_environnement370/lib/python3.7/site-packages/vext/env/__init__.py", line 99, in getsyssitepackages
    output = run()
  File "/home/pi/.pyenv/versions/3.7.0/envs/mon_environnement370/lib/python3.7/site-packages/vext/env/__init__.py", line 42, in call_f
    output = subprocess.check_output(cmd, env=env).decode('utf-8')
  File "/home/pi/.pyenv/versions/3.7.0/lib/python3.7/subprocess.py", line 376, in check_output
    **kwargs).stdout
  File "/home/pi/.pyenv/versions/3.7.0/lib/python3.7/subprocess.py", line 453, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/pi/.pyenv/versions/3.7.0/lib/python3.7/subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "/home/pi/.pyenv/versions/3.7.0/lib/python3.7/subprocess.py", line 1413, in _execute_child
    executable = os.fsencode(executable)
  File "/home/pi/.pyenv/versions/3.7.0/lib/python3.7/os.py", line 809, in fsencode
    filename = fspath(filename)  # Does type-checking of 'filename'.
TypeError: expected str, bytes or os.PathLike object, not NoneType
Traceback (most recent call last):
  File "<frozen importlib._bootstrap_external>", line 1219, in _path_importer_cache
KeyError: 'VextFinder.PATH_TRIGGER'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.pyenv/versions/mon_environnement370/bin/pip", line 7, in <module>
    from pip._internal import main
  File "/home/pi/.pyenv/versions/3.7.0/envs/mon_environnement370/lib/python3.7/site-packages/pip/_internal/__init__.py", line 19, in <module>
    from pip._vendor.urllib3.exceptions import DependencyWarning
  File "/home/pi/.pyenv/versions/3.7.0/envs/mon_environnement370/lib/python3.7/site-packages/pip/_vendor/urllib3/__init__.py", line 7, in <module>
    from .connectionpool import (
  File "/home/pi/.pyenv/versions/3.7.0/envs/mon_environnement370/lib/python3.7/site-packages/pip/_vendor/urllib3/connectionpool.py", line 30, in <module>
    from .connection import (
  File "/home/pi/.pyenv/versions/3.7.0/envs/mon_environnement370/lib/python3.7/site-packages/pip/_vendor/urllib3/connection.py", line 39, in <module>
    from .util.ssl_ import (
  File "/home/pi/.pyenv/versions/3.7.0/envs/mon_environnement370/lib/python3.7/site-packages/pip/_vendor/urllib3/util/__init__.py", line 4, in <module>
    from .request import make_headers
  File "/home/pi/.pyenv/versions/3.7.0/envs/mon_environnement370/lib/python3.7/site-packages/pip/_vendor/urllib3/util/request.py", line 9, in <module>
    import brotli as _unused_module_brotli  # noqa: F401
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 963, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 906, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1280, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1249, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1221, in _path_importer_cache
  File "<frozen importlib._bootstrap_external>", line 1197, in _path_hooks
  File "/home/pi/.pyenv/versions/3.7.0/envs/mon_environnement370/lib/python3.7/site-packages/vext/gatekeeper/__init__.py", line 227, in __init__
    sitedir = getsyssitepackages()
  File "/home/pi/.pyenv/versions/3.7.0/envs/mon_environnement370/lib/python3.7/site-packages/vext/env/__init__.py", line 99, in getsyssitepackages
    output = run()
  File "/home/pi/.pyenv/versions/3.7.0/envs/mon_environnement370/lib/python3.7/site-packages/vext/env/__init__.py", line 42, in call_f
    output = subprocess.check_output(cmd, env=env).decode('utf-8')
  File "/home/pi/.pyenv/versions/3.7.0/lib/python3.7/subprocess.py", line 376, in check_output
    **kwargs).stdout
  File "/home/pi/.pyenv/versions/3.7.0/lib/python3.7/subprocess.py", line 453, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/pi/.pyenv/versions/3.7.0/lib/python3.7/subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "/home/pi/.pyenv/versions/3.7.0/lib/python3.7/subprocess.py", line 1413, in _execute_child
    executable = os.fsencode(executable)
  File "/home/pi/.pyenv/versions/3.7.0/lib/python3.7/os.py", line 809, in fsencode
    filename = fspath(filename)  # Does type-checking of 'filename'.
TypeError: expected str, bytes or os.PathLike object, not NoneType

I use pyenv :
`$ curl -L https://raw.githubusercontent.com/yyuu/pyenv-installer/master/bin/pyenv-installer | bash`
`$ pyenv install 3.7.0`
`$ pyenv virtualenv 3.7.0 mon_environnement370`
`$ cd my_project`
`$ pyenv local mon_environnement370`
`$ pip install vext.gi`
and get the error...

How can I solve this issue ?
I am on :
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 9.11 (stretch)
Release:	9.11
Codename:	stretch

Best!

**Comment by stuaxo** [comment]
Can you also paste the content of ` /home/pi/.pyenv/versions/3.7.0/envs/mon_environnement370/lib/python3.7/site-packages/ruamel.yaml-0.16.5-py3.6-nspkg.pth` here, it looks like that may be what is confusing vext.

I usually use virtualenv / virtualenvwrapper, so it may be worth trying those instead ?

If not, then you could always try using python 3.6.

**Comment by Jackovic** [comment]
Here the content of /home/pi/.pyenv/versions/3.7.0/envs/mon_environnement370/lib/python3.7/site-packages/ruamel.yaml-0.16.5-py3.6-nspkg.pth :

import sys, types, os;has_mfs = sys.version_info > (3, 5);p = os.path.join(sys._getframe(1).f_locals['sitedir'], *('ruamel',));importlib = has_mfs and __import__('importlib.util');has_mfs and __import__('importlib.machinery');m = has_mfs and sys.modules.setdefault('ruamel', importlib.util.module_from_spec(importlib.machinery.PathFinder.find_spec('ruamel', [os.path.dirname(p)])));m = m or sys.modules.setdefault('ruamel', types.ModuleType('ruamel'));mp = (m or []) and m.__dict__.setdefault('__path__',[]);(p not in mp) and mp.append(p)

I tested with python 3.6.9 and I still get an error but I need to use python 3.7.
Best!

**Comment by Jackovic** [comment]
For information, here the output with python 3.6.9 :

Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting vext.gi
  Using cached https://files.pythonhosted.org/packages/9b/bb/67b71fd0f03acc9b5ed2b030c1934d56daf46b884699a24d170254a5fa25/vext.gi-0.7.0.tar.gz
Collecting vext>=0.7.0 (from vext.gi)
  Using cached https://www.piwheels.org/simple/vext/vext-0.7.3-py3-none-any.whl
Collecting ruamel.yaml>=0.11.10 (from vext>=0.7.0->vext.gi)
  Using cached https://files.pythonhosted.org/packages/fa/90/ecff85a2e9c497e2fa7142496e10233556b5137db5bd46f3f3b006935ca8/ruamel.yaml-0.16.5-py2.py3-none-any.whl
Collecting ruamel.yaml.clib>=0.1.2; platform_python_implementation == "CPython" and python_version < "3.8" (from ruamel.yaml>=0.11.10->vext>=0.7.0->vext.gi)
  Using cached https://files.pythonhosted.org/packages/92/28/612085de3fae9f82d62d80255d9f4cf05b1b341db1e180adcf28c1bf748d/ruamel.yaml.clib-0.2.0.tar.gz
Installing collected packages: ruamel.yaml.clib, ruamel.yaml, vext, vext.gi
  Running setup.py install for ruamel.yaml.clib ... done
  Running setup.py install for vext.gi ... error
    Complete output from command /home/pi/.pyenv/versions/3.6.9/envs/mon_environnement369/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-ungv4q6z/vext.gi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-9sw_br74/install-record.txt --single-version-externally-managed --compile --install-headers /home/pi/.pyenv/versions/3.6.9/envs/mon_environnement369/include/site/python3.6/vext.gi:
    Error processing line 1 of /home/pi/.pyenv/versions/3.6.9/envs/mon_environnement369/lib/python3.6/site-packages/ruamel.yaml-0.16.5-py3.6-nspkg.pth:
    
      Traceback (most recent call last):
        File "<frozen importlib._bootstrap_external>", line 1096, in _path_importer_cache
      KeyError: 'VextFinder.PATH_TRIGGER'
    
      During handling of the above exception, another exception occurred:
    
      Traceback (most recent call last):
        File "/home/pi/.pyenv/versions/3.6.9/lib/python3.6/site.py", line 168, in addpackage
          exec(line)
        File "<string>", line 1, in <module>
        File "<frozen importlib._bootstrap_external>", line 1006, in __contains__
        File "<frozen importlib._bootstrap_external>", line 984, in _recalculate
        File "<frozen importlib._bootstrap_external>", line 1126, in _get_spec
        File "<frozen importlib._bootstrap_external>", line 1098, in _path_importer_cache
        File "<frozen importlib._bootstrap_external>", line 1074, in _path_hooks
        File "/home/pi/.pyenv/versions/3.6.9/envs/mon_environnement369/lib/python3.6/site-packages/vext/gatekeeper/__init__.py", line 227, in __init__
          sitedir = getsyssitepackages()
        File "/home/pi/.pyenv/versions/3.6.9/envs/mon_environnement369/lib/python3.6/site-packages/vext/env/__init__.py", line 99, in getsyssitepackages
          output = run()
        File "/home/pi/.pyenv/versions/3.6.9/envs/mon_environnement369/lib/python3.6/site-packages/vext/env/__init__.py", line 42, in call_f
          output = subprocess.check_output(cmd, env=env).decode('utf-8')
        File "/home/pi/.pyenv/versions/3.6.9/lib/python3.6/subprocess.py", line 356, in check_output
          **kwargs).stdout
        File "/home/pi/.pyenv/versions/3.6.9/lib/python3.6/subprocess.py", line 423, in run
          with Popen(*popenargs, **kwargs) as process:
        File "/home/pi/.pyenv/versions/3.6.9/lib/python3.6/subprocess.py", line 729, in __init__
          restore_signals, start_new_session)
        File "/home/pi/.pyenv/versions/3.6.9/lib/python3.6/subprocess.py", line 1278, in _execute_child
          executable = os.fsencode(executable)
        File "/home/pi/.pyenv/versions/3.6.9/lib/python3.6/os.py", line 800, in fsencode
          filename = fspath(filename)  # Does type-checking of `filename`.
      TypeError: expected str, bytes or os.PathLike object, not NoneType
    
    Remainder of file ignored
    Error in sitecustomize; set PYTHONVERBOSE for traceback:
    TypeError: expected str, bytes or os.PathLike object, not NoneType
    Traceback (most recent call last):
      File "<frozen importlib._bootstrap_external>", line 1096, in _path_importer_cache
    KeyError: 'VextFinder.PATH_TRIGGER'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/pi/.pyenv/versions/3.6.9/envs/mon_environnement369/lib/python3.6/site-packages/setuptools/__init__.py", line 6, in <module>
        import distutils.core
      File "/home/pi/.pyenv/versions/3.6.9/lib/python3.6/distutils/core.py", line 16, in <module>
        from distutils.dist import Distribution
      File "/home/pi/.pyenv/versions/3.6.9/lib/python3.6/distutils/dist.py", line 18, in <module>
        from distutils.fancy_getopt import FancyGetopt, translate_longopt
      File "/home/pi/.pyenv/versions/3.6.9/lib/python3.6/distutils/fancy_getopt.py", line 12, in <module>
        import getopt
      File "/home/pi/.pyenv/versions/3.6.9/lib/python3.6/getopt.py", line 38, in <module>
        from gettext import gettext as _
      File "/home/pi/.pyenv/versions/3.6.9/lib/python3.6/gettext.py", line 49, in <module>
        import locale, copy, io, os, re, struct, sys
      File "/home/pi/.pyenv/versions/3.6.9/lib/python3.6/copy.py", line 60, in <module>
        from org.python.core import PyStringMap
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 951, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 894, in _find_spec
      File "<frozen importlib._bootstrap_external>", line 1157, in find_spec
      File "<frozen importlib._bootstrap_external>", line 1126, in _get_spec
      File "<frozen importlib._bootstrap_external>", line 1098, in _path_importer_cache
      File "<frozen importlib._bootstrap_external>", line 1074, in _path_hooks
      File "/home/pi/.pyenv/versions/3.6.9/envs/mon_environnement369/lib/python3.6/site-packages/vext/gatekeeper/__init__.py", line 227, in __init__
        sitedir = getsyssitepackages()
      File "/home/pi/.pyenv/versions/3.6.9/envs/mon_environnement369/lib/python3.6/site-packages/vext/env/__init__.py", line 99, in getsyssitepackages
        output = run()
      File "/home/pi/.pyenv/versions/3.6.9/envs/mon_environnement369/lib/python3.6/site-packages/vext/env/__init__.py", line 42, in call_f
        output = subprocess.check_output(cmd, env=env).decode('utf-8')
      File "/home/pi/.pyenv/versions/3.6.9/lib/python3.6/subprocess.py", line 356, in check_output
        **kwargs).stdout
      File "/home/pi/.pyenv/versions/3.6.9/lib/python3.6/subprocess.py", line 423, in run
        with Popen(*popenargs, **kwargs) as process:
      File "/home/pi/.pyenv/versions/3.6.9/lib/python3.6/subprocess.py", line 729, in __init__
        restore_signals, start_new_session)
      File "/home/pi/.pyenv/versions/3.6.9/lib/python3.6/subprocess.py", line 1278, in _execute_child
        executable = os.fsencode(executable)
      File "/home/pi/.pyenv/versions/3.6.9/lib/python3.6/os.py", line 800, in fsencode
        filename = fspath(filename)  # Does type-checking of `filename`.
    TypeError: expected str, bytes or os.PathLike object, not NoneType
    
    ----------------------------------------
Command "/home/pi/.pyenv/versions/3.6.9/envs/mon_environnement369/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-ungv4q6z/vext.gi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-9sw_br74/install-record.txt --single-version-externally-managed --compile --install-headers /home/pi/.pyenv/versions/3.6.9/envs/mon_environnement369/include/site/python3.6/vext.gi" failed with error code 1 in /tmp/pip-install-ungv4q6z/vext.gi/

But it would be super nice to install gi on python 3.7 in virtualenv.
Best!

**Comment by Jackovic** [comment]
Since :
`$ pip install vext.gi`
I am not able anymore to use command like :
`pip install --upgrade pip`
Because I get :

Error processing line 1 of /home/pi/.pyenv/versions/3.6.9/envs/mon_environnement369/lib/python3.6/site-packages/ruamel.yaml-0.16.5-py3.6-nspkg.pth:

  Traceback (most recent call last):
    File "<frozen importlib._bootstrap_external>", line 1096, in _path_importer_cache
  KeyError: 'VextFinder.PATH_TRIGGER'
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/home/pi/.pyenv/versions/3.6.9/lib/python3.6/site.py", line 168, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
    File "<frozen importlib._bootstrap_external>", line 1006, in __contains__
    File "<frozen importlib._bootstrap_external>", line 984, in _recalculate
    File "<frozen importlib._bootstrap_external>", line 1126, in _get_spec
    File "<frozen importlib._bootstrap_external>", line 1098, in _path_importer_cache
    File "<frozen importlib._bootstrap_external>", line 1074, in _path_hooks
    File "/home/pi/.pyenv/versions/3.6.9/envs/mon_environnement369/lib/python3.6/site-packages/vext/gatekeeper/__init__.py", line 227, in __init__
      sitedir = getsyssitepackages()
    File "/home/pi/.pyenv/versions/3.6.9/envs/mon_environnement369/lib/python3.6/site-packages/vext/env/__init__.py", line 99, in getsyssitepackages
      output = run()
    File "/home/pi/.pyenv/versions/3.6.9/envs/mon_environnement369/lib/python3.6/site-packages/vext/env/__init__.py", line 42, in call_f
      output = subprocess.check_output(cmd, env=env).decode('utf-8')
    File "/home/pi/.pyenv/versions/3.6.9/lib/python3.6/subprocess.py", line 356, in check_output
      **kwargs).stdout
    File "/home/pi/.pyenv/versions/3.6.9/lib/python3.6/subprocess.py", line 423, in run
      with Popen(*popenargs, **kwargs) as process:
    File "/home/pi/.pyenv/versions/3.6.9/lib/python3.6/subprocess.py", line 729, in __init__
      restore_signals, start_new_session)
    File "/home/pi/.pyenv/versions/3.6.9/lib/python3.6/subprocess.py", line 1278, in _execute_child
      executable = os.fsencode(executable)
    File "/home/pi/.pyenv/versions/3.6.9/lib/python3.6/os.py", line 800, in fsencode
      filename = fspath(filename)  # Does type-checking of `filename`.
  TypeError: expected str, bytes or os.PathLike object, not NoneType

Remainder of file ignored
Error in sitecustomize; set PYTHONVERBOSE for traceback:
TypeError: expected str, bytes or os.PathLike object, not NoneType
Failed checking if argv[0] is an import path entry
Traceback (most recent call last):
  File "/home/pi/.pyenv/versions/3.6.9/envs/mon_environnement369/lib/python3.6/site-packages/vext/gatekeeper/__init__.py", line 227, in __init__
    sitedir = getsyssitepackages()
  File "/home/pi/.pyenv/versions/3.6.9/envs/mon_environnement369/lib/python3.6/site-packages/vext/env/__init__.py", line 99, in getsyssitepackages
    output = run()
  File "/home/pi/.pyenv/versions/3.6.9/envs/mon_environnement369/lib/python3.6/site-packages/vext/env/__init__.py", line 42, in call_f
    output = subprocess.check_output(cmd, env=env).decode('utf-8')
  File "/home/pi/.pyenv/versions/3.6.9/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/home/pi/.pyenv/versions/3.6.9/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/pi/.pyenv/versions/3.6.9/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/home/pi/.pyenv/versions/3.6.9/lib/python3.6/subprocess.py", line 1278, in _execute_child
    executable = os.fsencode(executable)
  File "/home/pi/.pyenv/versions/3.6.9/lib/python3.6/os.py", line 800, in fsencode
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not NoneType
Traceback (most recent call last):
  File "<frozen importlib._bootstrap_external>", line 1096, in _path_importer_cache
KeyError: 'VextFinder.PATH_TRIGGER'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.pyenv/versions/mon_environnement369/bin/pip", line 7, in <module>
    from pip._internal import main
  File "/home/pi/.pyenv/versions/3.6.9/envs/mon_environnement369/lib/python3.6/site-packages/pip/_internal/__init__.py", line 19, in <module>
    from pip._vendor.urllib3.exceptions import DependencyWarning
  File "/home/pi/.pyenv/versions/3.6.9/envs/mon_environnement369/lib/python3.6/site-packages/pip/_vendor/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/home/pi/.pyenv/versions/3.6.9/envs/mon_environnement369/lib/python3.6/site-packages/pip/_vendor/urllib3/connectionpool.py", line 35, in <module>
    from .request import RequestMethods
  File "/home/pi/.pyenv/versions/3.6.9/envs/mon_environnement369/lib/python3.6/site-packages/pip/_vendor/urllib3/request.py", line 3, in <module>
    from .filepost import encode_multipart_formdata
  File "/home/pi/.pyenv/versions/3.6.9/envs/mon_environnement369/lib/python3.6/site-packages/pip/_vendor/urllib3/filepost.py", line 10, in <module>
    from .fields import RequestField
  File "/home/pi/.pyenv/versions/3.6.9/envs/mon_environnement369/lib/python3.6/site-packages/pip/_vendor/urllib3/fields.py", line 3, in <module>
    import mimetypes
  File "/home/pi/.pyenv/versions/3.6.9/lib/python3.6/mimetypes.py", line 31, in <module>
    import winreg as _winreg
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 951, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 894, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1157, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1126, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1098, in _path_importer_cache
  File "<frozen importlib._bootstrap_external>", line 1074, in _path_hooks
  File "/home/pi/.pyenv/versions/3.6.9/envs/mon_environnement369/lib/python3.6/site-packages/vext/gatekeeper/__init__.py", line 227, in __init__
    sitedir = getsyssitepackages()
  File "/home/pi/.pyenv/versions/3.6.9/envs/mon_environnement369/lib/python3.6/site-packages/vext/env/__init__.py", line 99, in getsyssitepackages
    output = run()
  File "/home/pi/.pyenv/versions/3.6.9/envs/mon_environnement369/lib/python3.6/site-packages/vext/env/__init__.py", line 42, in call_f
    output = subprocess.check_output(cmd, env=env).decode('utf-8')
  File "/home/pi/.pyenv/versions/3.6.9/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/home/pi/.pyenv/versions/3.6.9/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/pi/.pyenv/versions/3.6.9/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/home/pi/.pyenv/versions/3.6.9/lib/python3.6/subprocess.py", line 1278, in _execute_child
    executable = os.fsencode(executable)
  File "/home/pi/.pyenv/versions/3.6.9/lib/python3.6/os.py", line 800, in fsencode
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not NoneType
(mon_environnement369) pi@raspberrypi:~/versionOK $ pip install --up

Best!

**Comment by stuaxo** [comment]
Go into the site-packages directory and delete `vext*.pth` and things should be OK again.

Alternately just delete virtualenv and recreate it without vext.

**Comment by stuaxo** [comment]
It looks like mimetypes is conflicting with vext, when it trys to import winreg:

```
File "/home/pi/.pyenv/versions/3.6.9/envs/mon_environnement369/lib/python3.6/site-packages/pip/_vendor/urllib3/fields.py", line 3, in
import mimetypes
File "/home/pi/.pyenv/versions/3.6.9/lib/python3.6/mimetypes.py", line 31, in
import winreg as _winreg
...
File "/home/pi/.pyenv/versions/3.6.9/envs/mon_environnement369/lib/python3.6/site-packages/vext/gatekeeper/init.py", line 227, in init
```

Can you post a list of the packages you were trying to install in your virtualenv and I can try and reproduce this when I'm in front of my computer later.

**Comment by Jackovic** [comment]
> Go into the site-packages directory and delete `vext*.pth` and things should be OK again.
> 
> Alternately just delete virtualenv and recreate it without vext.

OK, deleting `vext*.pth` in site-packages directory do the job, I am now able to continue to install with pip.

**Comment by Jackovic** [comment]
> Can you post a list of the packages you were trying to install in your virtualenv and I can try and reproduce this when I'm in front of my computer later.

I am trying to install :
websockets, psutil and gi (to use it with gstreamer).
Thanks for help.
Best!

**Comment by Jackovic** [comment]
It is OK with websockets and psutil in my virtualenv with :
`$ pip install websokets`
and
`$ pip install psutil`

**Comment by stuaxo** [comment]
Vext should not cause a crash here, so I've made a PR that should fix that -

https://github.com/stuaxo/vext/pull/62

Getting vext working properly is a bit more tricky, so I'll have to leave the ticket open for now as I'm not sure how it's going to work.

**Comment by luni3359** [comment]
@Jackovic How did you get ``vext.gi`` to work? ``import gi`` just says ``No module named 'gi'``, and that's after deleting ``vext*.pth``, because if I don't both ``pip`` and ``python`` break.

**Comment by Joezeppe** [comment]
> Go into the site-packages directory and delete `vext*.pth` and things should be OK again.
> 
> Alternately just delete virtualenv and recreate it without vext.

This worked for me thanks

**Comment by stuaxo** [comment]
Attempting to install requirements-venv.txt from amdgpu in a fresh virtualenv reproduces the issue easily.

https://github.com/Ricks-Lab/amdgpu-utils/

**Comment by stuaxo** [comment]
There have been quite a few changes in 0.7.4 so it's worth trying again and seeing what the status in pyenv is.

It's possible it may do the same thing as virtualenv - install, but need enabling afterwards.

**Comment by SwiftWinds** [comment]
> it's worth trying again and seeing what the status in pyenv is.

Still doesn't work. You can easily reproduce the issue by using a pyenv virtualenv, then cloning this repo: https://github.com/google-coral/example-object-tracker and `cd gstreamer && bash install_requirements.sh`, then (since it needs to `import gi`), install both vext and vext.gi, then notice that running `python3 detect.py --tracker sort` errors out with `No module named 'gi'`.

**Comment by SwiftWinds** [comment]
![image](https://user-images.githubusercontent.com/12981958/126854375-bcc433dd-f697-40fe-8980-c28c32979834.png)
happens even with a `venv`

**Comment by SwiftWinds** [comment]
I'm on Ubuntu 21.04 btw
