### ISSUE TITLE
Vext.VTK for raspberry pi 4

### ISSUE THREAD

**Issue by TurBoss** [stuaxo/vext#75]
Hello,
I'm trying to install vtk using vext in a raspberry pi 4 

had success on  computer 

but this is shown when running pip install vext.vtk on the pi

same for python 2 and 3

```
$ pip3 install vext.vtk
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting vext.vtk
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Using cached https://files.pythonhosted.org/packages/54/05/d2c4a510e51545864f368643f38a3e02d852989f9055af87274489fd1a4e/vext.vtk-0.7.4.tar.gz
Collecting vext>=0.7.4 (from vext.vtk)
  Downloading https://www.piwheels.org/simple/vext/vext-0.7.4-py3-none-any.whl
Collecting ruamel.yaml>=0.11.10 (from vext>=0.7.4->vext.vtk)
  Using cached https://files.pythonhosted.org/packages/7e/39/186f14f3836ac5d2a6a042c8de69988770e8b9abb537610edc429e4914aa/ruamel.yaml-0.16.12-py2.py3-none-any.whl
Collecting ruamel.yaml.clib>=0.1.2; platform_python_implementation == "CPython" and python_version < "3.9" (from ruamel.yaml>=0.11.10->vext>=0.7.4->vext.vtk)
  Downloading https://www.piwheels.org/simple/ruamel-yaml-clib/ruamel.yaml.clib-0.2.2-cp37-cp37m-linux_armv7l.whl (550kB)
    100% |████████████████████████████████| 552kB 587kB/s 
Building wheels for collected packages: vext.vtk
  Running setup.py bdist_wheel for vext.vtk ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-4czy9tt_/vext.vtk/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-leinex0i --python-tag cp37:
  running bdist_wheel
  running build
  installing to build/bdist.linux-armv7l/wheel
  running install
  vext.vtk Install
  Not installing PTH file to real prefix
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-4czy9tt_/vext.vtk/setup.py", line 101, in <module>
      data_files=[("", vext_files)],
    File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 240, in run
      self.egg2dist(self.egginfo_dir, distinfo_dir)
    File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 337, in egg2dist
      raise ValueError(err)
  ValueError: Egg metadata expected at build/bdist.linux-armv7l/wheel/vext.vtk-0.7.4.egg-info but not found
  
  ----------------------------------------
  Failed building wheel for vext.vtk
  Running setup.py clean for vext.vtk
Failed to build vext.vtk
Installing collected packages: ruamel.yaml.clib, ruamel.yaml, vext, vext.vtk
  Running setup.py install for vext.vtk ... done
Successfully installed ruamel.yaml-0.16.12 ruamel.yaml.clib-0.2.2 vext-0.7.4 vext.vtk
```

thanks

**Comment by TurBoss** [comment]
python 2 log
```
$ pip install -U vext.vtk
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting vext.vtk
  Using cached vext.vtk-0.7.4.tar.gz (7.5 kB)
Requirement already satisfied, skipping upgrade: vext>=0.7.4 in /home/pi/.local/lib/python2.7/site-packages (from vext.vtk) (0.7.4)
Requirement already satisfied, skipping upgrade: ruamel.yaml>=0.11.10 in /home/pi/.local/lib/python2.7/site-packages (from vext>=0.7.4->vext.vtk) (0.16.12)
Requirement already satisfied, skipping upgrade: ruamel.ordereddict; platform_python_implementation == "CPython" and python_version <= "2.7" in /home/pi/.local/lib/python2.7/site-packages (from ruamel.yaml>=0.11.10->vext>=0.7.4->vext.vtk) (0.4.15)
Requirement already satisfied, skipping upgrade: ruamel.yaml.clib>=0.1.2; platform_python_implementation == "CPython" and python_version < "3.9" in /home/pi/.local/lib/python2.7/site-packages (from ruamel.yaml>=0.11.10->vext>=0.7.4->vext.vtk) (0.2.2)
Building wheels for collected packages: vext.vtk
  Building wheel for vext.vtk (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-__3Yey/vext-vtk/setup.py'"'"'; __file__='"'"'/tmp/pip-install-__3Yey/vext-vtk/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-qI1vpt
       cwd: /tmp/pip-install-__3Yey/vext-vtk/
  Complete output (23 lines):
  running bdist_wheel
  running build
  installing to build/bdist.linux-armv7l/wheel
  running install
  vext.vtk Install
  Not installing PTH file to real prefix
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-__3Yey/vext-vtk/setup.py", line 101, in <module>
      data_files=[("", vext_files)],
    File "/home/pi/.local/lib/python2.7/site-packages/setuptools/__init__.py", line 162, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/usr/lib/python2.7/dist-packages/wheel/bdist_wheel.py", line 240, in run
      self.egg2dist(self.egginfo_dir, distinfo_dir)
    File "/usr/lib/python2.7/dist-packages/wheel/bdist_wheel.py", line 337, in egg2dist
      raise ValueError(err)
  ValueError: Egg metadata expected at build/bdist.linux-armv7l/wheel/vext.vtk-0.7.4-py2.7.egg-info but not found
  ----------------------------------------
  ERROR: Failed building wheel for vext.vtk
  Running setup.py clean for vext.vtk
Failed to build vext.vtk
Installing collected packages: vext.vtk
    Running setup.py install for vext.vtk ... done
Successfully installed vext.vtk
```

**Comment by stuaxo** [comment]
I've got a rasperrypi 4, but no time to look at this for quite a while.

VTK works OK, outside the virtualenv, without vext ?

**Comment by TurBoss** [comment]
from pip it doesn't install there are no binaries for arm
but a guy managed to compile with qt5 support

**Comment by stuaxo** [comment]
Vext.vtk just lets you use your existing vext from a virtualenv, do you have it installed somewhere ?

**Comment by TurBoss** [comment]
oh ok so i need vtk on system first

thanks
