### ISSUE TITLE
ERROR: Failed building wheel for vext.gi

### ISSUE THREAD

**Issue by kierdwyn** [stuaxo/vext#83]
while install vext.gi using pip, I got the whole error message as below:

```bash
$ pip3 install vext.gi
WARNING: The directory '/home/xxx/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
Looking in indexes: https://pypi.douban.com/simple/
Collecting vext.gi
  Downloading https://pypi.doubanio.com/packages/6f/51/c83d41bda3b2766c4dc792f328078fdc1e1fa5742b6880301bf56db63878/vext.gi-0.7.4.tar.gz (2.9 kB)
Requirement already satisfied: vext>=0.7.4 in /usr/local/lib/python3.8/dist-packages (from vext.gi) (0.7.6)
Requirement already satisfied: ruamel.yaml>=0.11.10 in /usr/local/lib/python3.8/dist-packages (from vext>=0.7.4->vext.gi) (0.17.10)
Requirement already satisfied: ruamel.yaml.clib>=0.1.2 in /usr/local/lib/python3.8/dist-packages (from ruamel.yaml>=0.11.10->vext>=0.7.4->vext.gi) (0.2.6)
Building wheels for collected packages: vext.gi
  Building wheel for vext.gi (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-xbqde_ox/vext-gi_73215bf149e140ad9b748a01b6784db5/setup.py'"'"'; __file__='"'"'/tmp/pip-install-xbqde_ox/vext-gi_73215bf149e140ad9b748a01b6784db5/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-xljmc54l
       cwd: /tmp/pip-install-xbqde_ox/vext-gi_73215bf149e140ad9b748a01b6784db5/
  Complete output (23 lines):
  running bdist_wheel
  running build
  installing to build/bdist.linux-x86_64/wheel
  running install
  vext.gi Install
  Not installing PTH file to real prefix
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-xbqde_ox/vext-gi_73215bf149e140ad9b748a01b6784db5/setup.py", line 62, in <module>
      setup(
    File "/usr/local/lib/python3.8/dist-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.8/dist-packages/wheel/bdist_wheel.py", line 351, in run
      self.egg2dist(self.egginfo_dir, distinfo_dir)
    File "/usr/local/lib/python3.8/dist-packages/wheel/bdist_wheel.py", line 461, in egg2dist
      raise ValueError(err)
  ValueError: Egg metadata expected at build/bdist.linux-x86_64/wheel/vext.gi-0.7.4-py3.8.egg-info but not found
  ----------------------------------------
  ERROR: Failed building wheel for vext.gi
  Running setup.py clean for vext.gi
Failed to build vext.gi
Installing collected packages: vext.gi
    Running setup.py install for vext.gi ... done
Successfully installed vext.gi
```

**Comment by stuaxo** [comment]
What environment are you in, is it something like Docker ?

The message about `/home/xxx/.cache`not being owned by the current user is a bit odd, if you used `sudo` with pip before it might be worth making that directory owned by youself again (or just remove it so it can be recreated).
